version: 2

sources:
  # ============================================================
  #  STOCK PRICE RAW DATA SOURCE (Snowflake external load)
  # ============================================================
  - name: stock_data
    schema: raw
    database: stock_data
    description: >
      Raw price-level history for US equities, loaded via Snowpipe
      from Alpha Vantage TIME_SERIES_DAILY_ADJUSTED API exports.

    tables:
      - name: stock_price_data_raw
        description: >
          Raw pricing & corporate action data ingested from S3 using Snowpipe.
          Contains one row per ticker per trading date.

        tags: ["source", "stock_price"]

        external: false

        loaded_at_field: load_time

        freshness:
          warn_after: {count: 3, period: day}
          error_after: {count: 7, period: day}

        columns:
          - name: date
            description: Trading calendar date.
            tests:
              - not_null

          - name: open
            description: Opening price for the day.
          - name: high
            description: Intraday high price.
          - name: low
            description: Intraday low price.
          - name: close
            description: Closing price for the day.

          - name: adjusted_close
            description: >
              Adjusted close price including dividends & stock splits.

          - name: volume
            description: Daily trading volume.

          - name: dividend_amount
            description: Cash dividend paid on this date (if applicable).

          - name: split_coefficient
            description: >
              Factor representing stock splits or reverse splits.

          - name: ticker
            description: Equity ticker symbol.
            tests:
              - not_null

          - name: file_name
            description: Raw filename from S3 (Snowpipe metadata).

          - name: load_time
            description: Timestamp indicating when the row was loaded.

  # ============================================================
  #  COMPANY OVERVIEW RAW DATA SOURCE (Snowflake external load)
  # ============================================================
  - name: company_overview
    schema: raw
    database: stock_data
    description: >
      Raw company-level fundamental data from the Alpha Vantage
      OVERVIEW API, ingested quarterly.

    tables:
      - name: company_overview_raw
        description: >
          One record per company capturing fundamentals, valuation metrics,
          balance sheet summaries, and descriptive metadata.

        tags: ["source", "company_overview"]

        loaded_at_field: load_time

        freshness:
          warn_after: {count: 120, period: day}   # Quarterly
          error_after: {count: 180, period: day}

        columns:

          - name: ticker
            tests: [not_null]
            description: Ticker symbol for the company.

          - name: name
            description: Full registered name.
          - name: description
            description: Full business description.
          - name: exchange
            description: Stock exchange where listed.
          - name: currency
            description: Trading currency.
          - name: sector
            description: GICS sector classification.
          - name: industry
            description: GICS industry classification.
          - name: cik
            description: Central Index Key.

          - name: fiscal_year_end
            description: Fiscal year reporting end.

          - name: latest_quarter
            description: Last reported quarter.

          - name: market_cap
            description: Market capitalization.

          - name: shares_outstanding
            description: Number of outstanding common shares.

          - name: revenue_ttm
            description: Trailing twelve months revenue.

          - name: gross_profit_ttm
            description: Trailing twelve months gross profit.

          - name: ebitda
            description: Earnings before interest, taxes, depreciation, amortization.

          - name: pe_ratio
            description: Price-to-earnings ratio.

          - name: price_to_sales_ttm
            description: Price-to-sales ratio.

          - name: price_to_book_ratio
            description: Price-to-book ratio.

          - name: ev_to_ebitda
            description: Enterprise value to EBITDA.

          - name: ev_to_revenue
            description: Enterprise value to revenue.

          - name: beta
            description: Market beta estimate.

          - name: profit_margin
            description: Net profit margin.

          - name: operating_margin_ttm
            description: Operating margin trailing twelve months.

          - name: return_on_equity
            description: ROE measure.

          - name: return_on_assets
            description: ROA measure.

          - name: quarterly_earnings_growth_yoy
            description: Quarterly earnings year-over-year growth.

          - name: quarterly_revenue_growth_yoy
            description: Quarterly revenue year-over-year growth.

          - name: dividend_yield
            description: Company dividend yield.

          - name: dividend_per_share
            description: Annual dividend per share.

          - name: ex_dividend_date
            description: Last ex-dividend date.

          - name: dividend_date
            description: Dividend payable date.

          - name: load_time
            description: Timestamp for when row was loaded.

      