name: 'stock_data'
version: '1.0.0'
config-version: 2

profile: 'stock_data'

# -----------------------------------------------------------------------------
#  GLOBAL PROJECT CONFIGURATION
# -----------------------------------------------------------------------------
model-paths: ['models']
analysis-paths: ['analysis']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_packages'

# -----------------------------------------------------------------------------
#  MODEL CONFIGURATION
# -----------------------------------------------------------------------------
models:
  stock_data:

    # ----------------------------
    # STAGING MODELS
    # ----------------------------
    staging:
      +schema: STAGING
      +materialized: view
      +tags: ['staging']

    # ----------------------------
    # INTERMEDIATE MODELS
    # ----------------------------
    intermediate:
      +schema: INTERMEDIATE
      +materialized: table
      +tags: ['intermediate']

    # ----------------------------
    # ANALYTICS / FACT MODELS
    # ----------------------------
    analytics:
      +schema: ANALYTICS
      +materialized: table
      +tags: ['analytics']

# -----------------------------------------------------------------------------
#  TEST CONFIGURATION (OPTIONAL)
# -----------------------------------------------------------------------------
tests:
  +severity: warn

# -----------------------------------------------------------------------------
#  QUOTING (SAFE DEFAULTS)
# -----------------------------------------------------------------------------
quoting:
  database: false
  schema: false
  identifier: false


