version: 2

sources:
  - name: stock_data
    database: STOCK_DATA
    schema: RAW
    description: "Raw Snowpipe-ingested data from S3"

    tables:
      - name: stock_price_data_raw
        description: "Raw stock price OHLCV data."

      - name: company_overview_json_raw
        description: "Raw company fundamentals (quarterly)."

