---
version: 2

sources:
  - name: stock_data
    database: STOCK_DATA
    schema: RAW
    description: "Raw Snowpipe-ingested data from S3."

    tables:
      - name: stock_price_data_raw
        description: "Raw OHLCV stock price data loaded via Snowpipe."
        loaded_at_field: LOAD_TIME

        columns:
          - name: DATE
            tests:
              - not_null

          - name: TICKER
            tests:
              - not_null

          - name: CLOSE
            tests:
              - dbt_utils.accepted_range:
                  min_value: 0

          - name: VOLUME
            tests:
              - dbt_utils.accepted_range:
                  min_value: 0

      - name: company_overview_json_raw
        description: "Raw company fundamentals"
        loaded_at_field: LOAD_TIME

        columns:
          - name: LOAD_TIME
            tests:
              - not_null
